[tool.poetry]
name = "avato"
version = "0.2.0"
description = "Python client library for the Avato platform"
authors = ["decentriq <opensource@decentriq.ch>"]
readme = 'README.md'
repository = "https://github.com/decentriq/avato-python-client"
homepage = "https://github.com/decentriq/avato-python-client"

[tool.poetry.dependencies]
python = "3.7.*"

protobuf = "^3.11.0"
pyrebase4 = "^4.3.0"
requests = "^2.22.0"
asn1crypto = "^1.2.0"
certvalidator = "^0.11.1"
sgx-ias-structs = "^0.1.1"
chily = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^5.3.1"
