[tool.poetry]
name = "avato"
version = "0.5.3"
description = "Python client library for the Avato platform"
authors = ["decentriq <opensource@decentriq.ch>"]
readme = 'README.md'
repository = "https://github.com/decentriq/avato-python-client"
homepage = "https://github.com/decentriq/avato-python-client"

[tool.poetry.dependencies]
pycryptodome="^3.9.8"
typing-extensions="^3.7.4"
python = "^3.6"
protobuf = "^3.11.0"
requests = "^2.22.0"
asn1crypto = "^1.2.0"
certvalidator = "^0.11.1"
sgx-ias-structs = "^0.1.3"
chily = "^0.5.0"
pyOpenSSL = "^19.1.0"
hkdf = "0.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
